<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<PropertyGroup>
		<ArxYear Condition="'$(Configuration)' != ''">$([System.Text.RegularExpressions.Regex]::Match('$(Configuration)','20(2[56])').Value)</ArxYear>
		<ConfigSuffix Condition="'$(Configuration)' != ''">$([System.Text.RegularExpressions.Regex]::Match('$(Configuration)','(d)$').Value)</ConfigSuffix>
		<IsDebug Condition="'$(ConfigSuffix)' == 'd' or '$(Configuration)' == 'Debug'">true</IsDebug>
	</PropertyGroup>

	<PropertyGroup Condition="'$(ArxYear)' != ''">
		<AutoCADNetVersion Condition="'$(ArxYear)' == '2026' or '$(ArxYear)' == '2025'">20.25.0</AutoCADNetVersion>
		<TargetFramework Condition="'$(AutoCADNetVersion)' != '' and '$(TargetFramework)' == ''">net48</TargetFramework>

		<AssemblyName>$(MSBuildProjectName)$(ArxYear)</AssemblyName>
	</PropertyGroup>

	<ItemGroup Condition="'$(AutoCADNetVersion)' != ''">
		<PackageReference Include="ZWCAD.NetApi" Version="$(AutoCADNetVersion)" ExcludeAssets="runtime" />

		<PackageReference Include="PolySharp" Version="1.15.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<Reference Include="Microsoft.CSharp"/>
	</ItemGroup>
	
	<Target Name="ValidateArxConfig" BeforeTargets="Build">
		<Error Condition="'$(ArxYear)' != '' and !$(EnabledArxYears.Contains('$(ArxYear)'))"
			   Text="[配置错误] 年份 $(ArxYear) 未在 EnabledArxYears 中启用。" />
	</Target>

</Project>