<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<PropertyGroup>
		<ArxYear Condition="'$(Configuration)' != ''">$([System.Text.RegularExpressions.Regex]::Match('$(Configuration)',
		'20(1[5689]|2[01234567])').Value)</ArxYear>
		<ConfigSuffix Condition="'$(Configuration)' != ''">$([System.Text.RegularExpressions.Regex]::Match('$(Configuration)','(d)$').Value)</ConfigSuffix>
		<IsDebug Condition="'$(ConfigSuffix)' == 'd' or '$(Configuration)' == 'Debug'">true</IsDebug>
		<NetVersion Condition="'$(ArxYear)' == '2027' or '$(ArxYear)' == '2026' or '$(ArxYear)' == '2025'">NetCore</NetVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(ArxYear)' != ''">
		<AutoCADNetVersion Condition="'$(ArxYear)' == '2027'">26.0.0</AutoCADNetVersion>
		<AutoCADNetVersion Condition="'$(ArxYear)' == '2026' or '$(ArxYear)' == '2025'">25.0.1</AutoCADNetVersion>
		<AutoCADNetVersion Condition="'$(ArxYear)' == '2024' or '$(ArxYear)' == '2023' or '$(ArxYear)' == '2022' or '$(ArxYear)' == '2021'">24.3.0</AutoCADNetVersion>
		<AutoCADNetVersion Condition="'$(ArxYear)' == '2020' or '$(ArxYear)' == '2019' or '$(ArxYear)' == '2018' or '$(ArxYear)' == '2017' or '$(ArxYear)' == '2016' or '$(ArxYear)' == '2015'">23.0.0</AutoCADNetVersion>

		<TargetFramework Condition="'$(ArxYear)' == '2027'">net10.0-windows</TargetFramework>
		<TargetFramework Condition="'$(ArxYear)' == '2026' or '$(ArxYear)' == '2025'">net8.0-windows</TargetFramework>
		<TargetFramework Condition="'$(NetVersion)' != 'NetCore'">net48</TargetFramework>

		<AssemblyName>$(MSBuildProjectName)$(ArxYear)</AssemblyName>
	</PropertyGroup>

	<ItemGroup Condition="'$(AutoCADNetVersion)' != ''">
		<PackageReference Include="AutoCAD.NET" Version="$(AutoCADNetVersion)" ExcludeAssets="runtime" />

		<PackageReference Include="PolySharp" Version="1.15.0 " Condition="'$(NetVersion)' != 'NetCore'">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<Reference Include="Microsoft.CSharp" Condition="'$(NetVersion)' != 'NetCore'"/>
	</ItemGroup>

	<ItemGroup Condition="'$(ArxYear)' == '2027'">
    	<FrameworkReference Include="Microsoft.WindowsDesktop.App" />
	</ItemGroup>
	
	<Target Name="ValidateArxConfig" BeforeTargets="Build">
		<Error Condition="'$(ArxYear)' != '' and !$(EnabledArxYears.Contains('$(ArxYear)'))"
			   Text="[配置错误] 年份 $(ArxYear) 未在 EnabledArxYears 中启用。" />
	</Target>

</Project>